### PR TITLE
Pkgdown

### PR DESCRIPTION
**Pull request by peterdesmet**
Don't merge yet, need to finish checklist below.

- [x] Pass checks
- [x] Build site
- [x] Add `pkgdown.yml` @peterdesmet 
- [x] @adokter Can the `doc` directory be removed? It seems to contain some generated html files, but I'm not sure what they are for. Typically, everything should be written to the `docs` directory (automatically, with pkgdown).
- [x] Move vignette
- [x] Decide on title
- [x] Add links to authors
- [x] Update README
- [x] Add GloBAM as funder

### CODE REVIEW

**Comment by adokter** [comment]
Yes doc can be removed, it's gone on master now

**Comment by adokter** [comment]
You'll notice that quite a few documented functions are hidden in the package, we only need website documentation for the exposed functions that appear in the index that you can pull up with `?vol2birdR`

**Comment by peterdesmet** [comment]
@adokter is https://github.com/adokter/vol2birdR/blob/main/vignettes/package.Rmd supposed to be an introductory vignette about the package? If so, I'll rename it `vol2birdR` so it is used as the Get started article.

@adokter @andershenja I can add urls for both of you as author. Do I choose:

- http://adriaandokter.com
- https://www.linkedin.com/in/anders-henja-03a1b05

**Comment by peterdesmet** [comment]
And do I name the vignette `Introduction to vol2birdR` or `Using vol2birdR`. Currently both titles are used and they need to be the same.

**Comment by adokter** [comment]
Let's do `Introduction to vol2birdR`. The vignette still needs to be updated, as it uses functions that are now hidden, and don't include the two main user-exposed functions `vol2bird()` and `vol2bird_config()`

**Pull request merged**
